### ISSUE TITLE
Plugins not starting properly ?

### ISSUE THREAD

**Issue by colindaven** [cmdcolin/gccontent#2]
Hi,

nice ideas on these plugins.

Trying them out in a dev version, I haven't got them going reliably yet.
1. 
   git clone into plugins

Result:
JBrowse_test$ ls -1 plugins/
RegexSequenceSearch
gccontent
sashimiplot

2.
jbrowse.conf

  ## uncomment and edit the example below to enable one or more 
  ## JBrowse plugins
 [ plugins.gccontent ]
 location = plugins/gccontent
 [ plugins.sashimiplot ]
 location = plugins/sashimiplot

3.
data/trackList.json stanzas:

```
    {
      "storeClass" : "JBrowse/Store/SeqFeature/IndexedFasta",
      "type": "GCContent/View/Track/GCContentXY",
      "label": "GCContent",
      "urlTemplate" : "../SBKv2con.fa",
      "bicolor_pivot": 0.5
    },
    {
  "label": "star_sashimi_junctions",
  "storeClass": "JBrowse/Store/SeqFeature/BAM",
  "type": "SashimiPlot/View/Track/Sashimi",
  "urlTemplate": "tracks/STAR1Aligned.out_s.bam",
    "chunkSizeLimit": 50000000,
    "key" : "tEST sashimi",
    "useXS": true
    }
```

Output on clicking track - nothing - I would expect a "datafile not found" message or similar if the BAM or FASTA are not being found. Am I missing something here? 

Thanks!
Colin

**Comment by cmdcolin** [comment]
Sorry was out on vacation last week

I should probably expand on the "how to install" section

Generally this looks exactly right, except I would use

```
[ plugins.GCContent ]
location = plugins/gccontent
```

The name of the plugin is officially "GCContent" instead of gccontent, and some of the paths depend on that inside the code :)

Alternatively, and I guess this demonstrates how there are many ways to include the plugin, you can just name the folder plugins/GCContent and plugins/SashimiPlot in the first place, and then just say this in your jbrowse.conf

```
plugins += GCContent
plugins += SashimiPlot
```

Equivalently, in the jbrowse_conf.json, that would mean just having

`"plugins": ["GCContent", "SashimiPlot"]`

So it is essentailly just an array of folder names to look for in the plugins directory

Similarly, the .conf format representation as

```
[ plugins.GCContent ]
location = plugins/gccontent
```

Would be equivalent to this in the json format

```
"plugins": [{
"name": "GCContent",
"location": "plugins/gccontent"
}]
```

This is similar, but it is an array of objects with the plugin name and location.

This is actually such a nuanced type of thing (especially considering the different .conf and json representations) that I will add it to the new JBrowse FAQ :)

**Comment by cmdcolin** [comment]
See http://gmod.org/wiki/JBrowse_FAQ#How_do_I_install_a_plugin

Let me know if there are any other issues!

**Comment by colindaven** [comment]
Hi, thanks Colin, very much appreciated. The plugins look great.

Perhaps you can add the following example SequenceChunks to the gccontent github example. I couldn't get the IndexedFasta to work but would vastly prefer to use the already imported SequenceChunks anyway and many others might prefer this too (I missed the fact you could use SequenceChunks on my first attempt.

```
    {
      "storeClass" : "JBrowse/Store/SeqFeature/SequenceChunks",
      "type": "GCContent/View/Track/GCContentXY",
      "label": "GCContentXY",
      "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
      "bicolor_pivot": 0.5
    },
```

Cheers,
colin
