### ISSUE TITLE
Can not use in JBrowse 1.14.1

### ISSUE THREAD

**Issue by tao-bioinfo** [cmdcolin/gccontent#6]
When I turn on the plugin, the JBrowse instance crashes:

```
Failed to load resource: GCContent/View/Track/GCContentXY.
```

However, I confirm that `GCContent/js/View/Track/GCContentXY.js` exists

**Comment by cmdcolin** [comment]
Can you detail your setup? It works ok for me. The only change after 1.14 is that you have to use a -dev build of jbrowse and rerun setup.sh after you come the repo to your plugin directory

**Comment by tao-bioinfo** [comment]
Yes, Now I am running `setup.sh`, however it stops at `installing node.js dependencies and building with webpack ...` for more than half an hour...

Why the new version of Jbrowse is so difficult to use...

**Comment by cmdcolin** [comment]
I guess the main thing is that newer JBrowse switched to webpack for compiling and webpack needs to know about all modules at compile time (hence the need to rebuild jbrowse when adding a new plugin module).


If it is stuck, then you might consider cancelling build, rm -rf node_modules, and re-run setup.sh again! Hopefully the webpack build should be more painless because it is a more modern and nice system

**Comment by tao-bioinfo** [comment]
Perhaps we can discuss more at https://github.com/GMOD/jbrowse/issues/1051
